version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nft-app_container
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=postgres_container
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_NAME=postgres
      - POSTGRES_PORT=5432
  db:
    image: postgres:16-alpine
    container_name: postgres_container
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"