// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"nft-api/app/adapter/handler"
	"nft-api/app/infrastructure"
	"nft-api/app/usecase"
)

// Injectors from wire.go:

func InitializeWire() (*handler.VoiceHandler, error) {
	voiceRepository := infrastructure.NewVoiceRepository()
	voiceUsecase := usecase.NewVoiceUsecase(voiceRepository)
	voiceHandler := handler.NewVoiceHandler(voiceUsecase)
	return voiceHandler, nil
}
