// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"nft-api/app/adapter/handler"
	"nft-api/app/infrastructure/repository"
	"nft-api/app/usecase"
)

// Injectors from wire.go:

// MEMO: 再宣言エラーが発生してしまうため、wireで自動生成後は関数はコメントアウトしておく
func InitializeVoiceHandler() (*handler.VoiceHandler, error) {
	voiceRepository := repository.NewVoiceRepository()
	voiceUseCase := usecase.NewVoiceUseCase(voiceRepository)
	voiceHandler := handler.NewVoiceHandler(voiceUseCase)
	return voiceHandler, nil
}

func InitializeEthereumHandler() (*handler.EthereumHandler, error) {
	ethereumRepository := repository.NewEthereumRepository()
	ethereumUseCase := usecase.NewEthereumUseCase(ethereumRepository)
	ethereumHandler := handler.NewEthereumHandler(ethereumUseCase)
	return ethereumHandler, nil
}
